export const theme = {
  primaryButtonBackgroundColor: "var(--brandGreen100)",
  primaryButtonTextColor: "var(--brandWhite100)",
  primaryButtonFontWeight: "500",
  primaryButtonBorder: "none",
  primaryButtonHoveredBackgroundColor: "var(--brandGreen90)",
  primaryButtonHoveredTextColor: "var(--brandWhite100)",
  primaryButtonHoveredFontWeight: "300",
  primaryButtonHoveredBorder: "none",

  secondaryButtonBackgroundColor: "var(--brandBlack10)",
  secondaryButtonTextColor: "var(--brandBlack100)",
  secondaryButtonBorder: "none",
  secondaryButtonHoveredBackgroundColor: "var(--brandBlack10)",
  secondaryButtonHoveredTextColor: "var(--brandBlack100)",
  secondaryButtonHoveredBorder: "none",

  h1Color: "var(--brandBlack100)",
  h2Color: "var(--brandBlack100)",
  h3Color: "var(--brandBlack100)",
  h4Color: "var(--brandBlack100)",
  h5Color: "var(--brandBlack100)",
  h6Color: "var(--brandBlack100)",
  paragraphColor: "var(--brandBlack100)",
  linkColor: "var(--brandGreen100)",
}
